"""Database cren

Revision ID: a070fecf1016
Revises: 
Create Date: 2023-07-05 22:42:03.424550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import func
from sqlalchemy.dialects import postgresql

from db.sql import update_subscription_history, update_payment_history, update_subscription_type_history, \
    update_refund_history

revision = 'a070fecf1016'
down_revision = None
branch_labels = None
depends_on = None

subscription_history_trigger = PGTrigger(
    schema="content",
    signature="subscription_history_trigger",
    on_entity="content.subscription_history",
    definition=update_subscription_history
)
payment_history_trigger = PGTrigger(
    schema="content",
    signature="payment_history_trigger",
    on_entity="content.payment_history",
    definition=update_payment_history
)
subscription_type_history_trigger = PGTrigger(
    schema="content",
    signature="subscription_type_history_trigger",
    on_entity="content.subscription_type_history",
    definition=update_subscription_type_history
)
refund_history_trigger = PGTrigger(
    schema="content",
    signature="refund_history_trigger",
    on_entity="content.refund_history",
    definition=update_refund_history
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('person_id', postgresql.UUID(), nullable=True),
    sa.Column('start_date', sa.TIMESTAMP(), default=func.now()),
    sa.Column('end_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('subscription_type', sa.String(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['content.person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('person_id', postgresql.UUID(), nullable=True),
    sa.Column('subscription_id', postgresql.UUID(), nullable=False),
    sa.Column('payment_amount', sa.DECIMAL(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=False),
    sa.Column('payment_method_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['content.person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription_type',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('subscription_id', postgresql.UUID(), nullable=True),
    sa.Column('refund_amount', sa.DECIMAL(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refund',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('payment_id', postgresql.UUID(), nullable=True),
    sa.Column('refund_amount', postgresql.UUID(), nullable=False),
    sa.Column('payment_amount', sa.DECIMAL(), nullable=False),
    sa.Column('refund_status', sa.String(), nullable=False),
    sa.Column('external_refund_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['refund_amount'], ['subscription.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription_history',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('person_id', postgresql.UUID(), nullable=True),
    sa.Column('start_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('end_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('subscription_type', sa.String(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('operation_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('operation_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['content.person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_history',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('person_id', postgresql.UUID(), nullable=True),
    sa.Column('subscription_id', postgresql.UUID(), nullable=False),
    sa.Column('payment_amount', sa.DECIMAL(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=False),
    sa.Column('payment_method_id', sa.String(), nullable=False),
    sa.Column('operation_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('operation_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['content.person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription_type_history',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('subscription_id', postgresql.UUID(), nullable=True),
    sa.Column('refund_amount', sa.DECIMAL(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('operation_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('operation_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refund_history',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('payment_id', postgresql.UUID(), nullable=True),
    sa.Column('refund_amount', postgresql.UUID(), nullable=False),
    sa.Column('payment_amount', sa.DECIMAL(), nullable=False),
    sa.Column('refund_status', sa.String(), nullable=False),
    sa.Column('external_refund_id', sa.String(), nullable=False),
    sa.Column('operation_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('operation_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['refund_amount'], ['subscription.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_trigger(subscription_history_trigger)
    op.create_trigger(payment_history_trigger)
    op.create_trigger(subscription_type_history_trigger)
    op.create_trigger(refund_history_trigger)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refund')
    op.drop_table('subscription_type')
    op.drop_table('payment')
    op.drop_table('subscription')
    op.drop_table('refund_history')
    op.drop_table('subscription_type_history')
    op.drop_table('payment_history')
    op.drop_table('subscription_history')
    op.drop_trigger(subscription_history_trigger)
    op.drop_trigger(payment_history_trigger)
    op.drop_trigger(subscription_type_history_trigger)
    op.drop_trigger(refund_history_trigger)
    # ### end Alembic commands ###
