version: '3.9'

services:

  sender:
    container_name: sender
#    restart: always
    build:
      context: .
      dockerfile: ./rabbit_api/sender/Dockerfile
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${NOTIFICATION_POSTGRES_USER}
      POSTGRES_PASSWORD: ${NOTIFICATION_POSTGRES_PASSWORD}
      POSTGRES_HOST: ${NOTIFICATION_POSTGRES_HOST}
    networks:
      - cinema_network

networks:
  cinema_network:
    driver: bridge