version: '3.9'
services:
  db:
    image: postgres:15.2-alpine
    hostname: db
    volumes:
      - ./_postgres_data:/var/lib/postgresql/data/
    restart: on-failure
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${DB_NAME}", "-U", "${DB_USER}"]
      interval: 3s
      timeout: 5s
      retries: 30
    deploy:
      resources:
        limits:
          memory: 1024M
    networks:
      - cinema_network

  redis_cache:
    build: redis_config
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - ./_redis_data:/opt/redis/db
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    networks:
      - cinema_network

  elasticsearch:
    image: elasticsearch:7.17.9
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms900m -Xmx900m"
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    hostname: elasticsearch
    volumes:
      - ./_es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50
    networks:
      - cinema_network


  etl_service_films:
    build: etl
    env_file:
      - .env
    environment:
      - UPLOADED_INDEX=films
    volumes:
      - ./db:/opt/app/db:ro
      - ./structure_migration:/opt/app/structure_migration:ro
    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    networks:
      - cinema_network

  etl_service_genres:
    build: etl
    env_file:
      - .env
    environment:
      - UPLOADED_INDEX=genres
    volumes:
      - ./db:/opt/app/db:ro
      - ./structure_migration:/opt/app/structure_migration:ro
    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    networks:
      - cinema_network

  etl_service_persons:
    build: etl
    env_file:
      - .env
    environment:
      - UPLOADED_INDEX=persons
    volumes:
      - ./db:/opt/app/db:ro
      - ./structure_migration:/opt/app/structure_migration:ro
    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    networks:
      - cinema_network

  fastapi_service:
    build: fastapi-solution
    image: fastapi-image
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      redis_cache:
        condition: service_healthy
    healthcheck:
      test: curl -s http://localhost:8000/api/v1/status >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50
    networks:
      - cinema_network


  nginx_service:
    image: nginx:1.23
    hostname: nginx
    volumes:
      - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_config/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
    restart: on-failure
    depends_on:
      fastapi_service:
        condition: service_healthy
    healthcheck:
      test: curl -s http://localhost:80/api/v1/status >/dev/null || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - cinema_network

  keycloak-postgres:
    image: postgres:15.2-alpine
    hostname: keycloak-postgres
    volumes:
      - ./_postgres_data_cloak:/var/lib/postgresql/data/
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGUSER: postgres
      PGPORT: 5433
    healthcheck:
      test: [ "CMD", "pg_isready", "-p", "5433" ]
      interval: 3s
      timeout: 5s
      retries: 30
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - cinema_network

  keycloak:
    build: keycloak
    container_name: keycloak
    hostname: keycloak
    command:
      - start --hostname-strict-https false --hostname-strict false --proxy edge --http-enabled true --import-realm --spi-user-profile-legacy-user-profile-read-only-attributes *_RES_ACCESS_MODE
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./keycloak/import/realm-export.json
        target: /opt/keycloak/data/import/realm-export.json
        read_only: true
      - type: bind
        source: ./keycloak/keycloak.conf
        target: /opt/keycloak/conf/keycloak.conf
        read_only: true
    ports:
      - "8080:8080"
    depends_on:
      keycloak-postgres:
        condition: service_healthy
    networks:
      - cinema_network

  flaskapi-solution:
    build: flaskapi-solution
    hostname: flaskapi
    env_file:
      - .env
    ports:
      - "8001:8001"
    depends_on:
      keycloak-postgres:
        condition: service_healthy
      redis_cache:
        condition: service_healthy
    networks:
      - cinema_network

  tests_auth:
    build: tests_auth/functional
    volumes:
      - ./tests_auth:/tests_auth
    env_file:
      - .env
    depends_on:
      nginx_service:
        condition: service_started
      fastapi_service:
        condition: service_started
      elasticsearch:
        condition: service_healthy
      redis_cache:
        condition: service_healthy
    networks:
      - cinema_network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.2
    depends_on:
      - elasticsearch
    environment:
      XPACK_MONITORING_ENABLED: "false"
      ES_HOST: "eslogs:9201"
    ports:
      - "5044:5044/udp"
    volumes:
      - ./logstash/logstash.conf:/config/logstash.conf:ro
    command: logstash -f /config/logstash.conf
    networks:
      - cinema_network

  elasticsearch_logs:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    hostname: eslogs
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - http.port=9201 #different port
      - "ES_JAVA_OPTS=-Xms900m -Xmx900m"
    ports:
      - "9201:9201"
    volumes:
      - /_es_data_logs:/tmp/elasticsearch/data
    networks:
      - cinema_network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    ports:
      - "5601:5601"
    environment:
      elasticsearch.hosts: "elasticsearch:9201"
    depends_on:
      - elasticsearch_logs
    networks:
      - cinema_network

volumes:
  _postgres_data:
  _es_data:
  _redis_data:
  _postgres_data_cloak:
  tests_auth:
  _es_data_logs:
  logstash:

networks:
  cinema_network:
    driver: bridge