version: '3.9'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.10
    hostname: logstash
    depends_on:
      - elasticsearch_logs
    environment:
      XPACK_MONITORING_ENABLED: "false"
    ports:
      - "12201:12201/udp"
    volumes:
      - ./logstash/logstash.conf:/config/logstash.conf:ro
    command: logstash -f /config/logstash.conf
    networks:
      - cinema_network

  elasticsearch_logs:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    hostname: eslogs
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - http.port=9201 #different port
      - "ES_JAVA_OPTS=-Xms900m -Xmx900m"
    ports:
      - "9201:9201"
    volumes:
      - ./_es_data_logs:/usr/share/elasticsearch/data
    networks:
      - cinema_network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS="http://eslogs:9201"
    depends_on:
      - elasticsearch_logs
    networks:
      - cinema_network

  fluentd_service:
    build: fluentd
    hostname: fluentd_service
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - cinema_network

volumes:
  _es_data_logs:
  logstash:

networks:
  cinema_network:
    driver: bridge