version: '3.9'
services:
  keycloak-postgres:
    image: postgres:15.3-alpine
    hostname: keycloak-postgres
    volumes:
      - ./_postgres_data_cloak:/var/lib/postgresql/data/
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGUSER: postgres
      PGPORT: 5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-p", "5432" ]
      interval: 3s
      timeout: 5s
      retries: 30
    deploy:
      resources:
        limits:
          memory: 256M
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "host.docker.internal:24224"
        tag: "postgres_keycloak"
    networks:
      - cinema_network

  keycloak:
    build: keycloak
    container_name: keycloak
    hostname: keycloak
    command:
      - start --hostname-strict-https false --hostname-strict false --proxy edge --http-enabled true --import-realm --spi-user-profile-legacy-user-profile-read-only-attributes *_RES_ACCESS_MODE
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./keycloak/import/realm-export.json
        target: /opt/keycloak/data/import/realm-export.json
        read_only: true
      - type: bind
        source: ./keycloak/keycloak.conf
        target: /opt/keycloak/conf/keycloak.conf
        read_only: true
    ports:
      - "8080:8080"
    depends_on:
      keycloak-postgres:
        condition: service_healthy
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "host.docker.internal:24224"
        tag: "keycloak_service"
    networks:
      - cinema_network

  flaskapi-solution:
    build: flaskapi-solution
    hostname: flaskapi
    env_file:
      - .env
    ports:
      - "8001:8001"
    depends_on:
      keycloak-postgres:
        condition: service_healthy
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "host.docker.internal:24224"
        tag: "flaskapi_auth"
    networks:
      - cinema_network

volumes:
  _postgres_data_cloak:


networks:
  cinema_network:
    driver: bridge