"""Database creatin

Revision ID: 123e260f185b
Revises: 64eb10287639
Create Date: 2023-06-09 21:48:48.461821

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '123e260f185b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
                    sa.Column('id', sa.Integer(), primary_key=True),
                    sa.Column('event', sa.String()),
                    sa.Column('instant_event', sa.Boolean()),
                    sa.Column('title', sa.String()),
                    sa.Column('text', sa.Text()),
                    schema='content'
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('templates', schema='content')
    # ### end Alembic commands ###
