"""fill_data

Revision ID: 5re66ro7vbn9
Revises: 
Create Date: 2023-06-22 22:35:03.846372

"""
from alembic import op
from sqlalchemy import DDL

from migrations.data.fill_data import insert_templates


revision = '5re66ro7vbn9'
down_revision = '123e260f185b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(insert_templates)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    drop_schema = DDL('''
        delete from content.templates;
    ''')
    drop_schema(target=None, bind=op.get_bind())
    # ### end Alembic commands ###
