name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [ "3.7", "3.8", "3.9", "3.10" ]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        mkdir -p flake-report
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 ./analytic-solution --count --statistics --format=html --htmldir=flake-report

    - name: Upload flake reports as an artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: flake-reports
        path: |
          flake-report

    - name: Check mypy
      if: always()
      run: |
        mypy ./analytic-solution

  notify:
    runs-on: ubuntu-latest
    if: always()
    needs: build

    steps:
    - name: Send Telegram Message Ok
      uses: appleboy/telegram-action@master
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      with:
        to: ${{ secrets.TELEGRAM_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: html
        message: |
          <b>Yandex cinema</b>
          <b>Build is finished</b>
          Repository: ${{ github.repository }}
          Commit: <a href="${{ github.event.head_commit.url }}">${{ github.event.head_commit.message }}</a>
          Author: ${{ github.actor }}
          Status: ${{ needs.build.result }}
          <a href="https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}">Run details</a>
